#!/usr/bin/env ruby -w

def run(command)
  system(command) || abort("`#{command}` failed")
end

run("gem install bundler") if `gem list bundler | grep bundler`.empty?

run "bundle check || bundle install"
run "rake"